# Changes here will be overwritten by Copier
_commit: 47f880e
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: js
add_wiki: false
email: t.paine154@gmail.com
github: 1kbgz
project_description: Home Automation
project_name: tadaima
python_version_primary: '3.11'
team: the tadaima authors
