# Changes here will be overwritten by Copier
_commit: 3d9a86d
_src_path: https://github.com/python-project-templates/base.git
add_extension: js
email: 3105306+timkpaine@users.noreply.github.com
github: timkpaine
project_description: Home Automation
project_name: tadaima
python_version_primary: '3.11'
team: the tadaima authors
